{ config, pkgs, ... } :
{
    wayland.windowManager.hyprland = {
      enable = true;
      xwayland.enable = true;
      settings = {

          autogenerated = 0;

          "exec-once" = [
                "waybar"
                "hyprpaper"
          ];
          
          monitor = [
                "DP-1, 1920x1080@144,auto, 1"
                "HDMI-A-1, disable" #1920x1080@75, 1920x0, auto
          ];

          input = {
              kb_layout = "us,ru";
              kb_options = "grp:win_space_toggle"; #caps:swapescape
          };    

          general = {
              "gaps_out" = 0;
              "gaps_in" = 0;
              "col.active_border" = "rgba(00ff99ee) "; #rgba(33ccffee)
          };

          cursor = {
              "no_hardware_cursors" = true;
          };

          #env = [
          ##  "HYPRCURSOR_THEME, X11-Default-Black"
          #  "LIBVA_DRIVER_NAME,nvidia"
          #  "__GLX_VENDOR_LIBRARY_NAME,nvidia"
          #];


          #variables

          "$mod" = "SUPER";
          "$menu" = "fuzzel --show drun";
          "$terminal" = "foot";
          "$fileManger" = "foot -e yazi";
          "$browser" = "firefox";

          bind =
          [
            #apps
            "$mod, RETURN, exec, $terminal"
            "$mod, E, exec, $terminal -e yazi"
            "$mod, R, exec, $menu, "
            "$mod, B, exec, $browser"
            #interections
            "$mod, Q, killactive, "
            "$mod, F, fullscreen, "
            "$mod, M, exit, "
            "$mod, V, togglefloating, "
            "$mod, P, pseudo, "
            #movings
            #"$mod, J, togglesplit"
            "$mod, H, movefocus, l"
            "$mod, J, movefocus, d"
            "$mod, K, movefocus, u"
            "$mod, L, movefocus, r"
            "$mod SHIFT, H, movewindow, l"
            "$mod SHIFT, J, movewindow, d"
            "$mod SHIFT, K, movewindow, u"
            "$mod SHIFT, L, movewindow, r"

            #screenshots
            "$mod, S, exec, hyprshot -m output -f -o ~/Pictures/Screenshots"
            "$mod SHIFT, S, exec, hyprshot -m region -f -o ~/Pictures/Screenshots"

            #workspaces
            "$mod, 0, workspace, 10"
            "$mod SHIFT, 0, movetoworkspace, 10"
          ]
          ++ (
            # workspaces
            # binds $mod + [shift +] {1..9} to [move to] workspace {1..9}
            builtins.concatLists (builtins.genList (i:
                let ws = i + 1;
                in [
                    "$mod, ${toString (1+i)}, workspace, ${toString ws}"
                    "$mod SHIFT, ${toString (1+i)}, movetoworkspace, ${toString ws}"
                ]
            ) 9)
          );



          bindm = [
              "$mod, mouse:272, movewindow"
              "$mod, mouse:273, resizewindow"
              "$mod ALT, mouse:272, resizewindow" 
          ];

          windowrule = [
              "opacity 0.75, foot"
              "noblur on, foot"
              "opacity 0.94, firefox"
              "opacity 0.94, obsidian"
              "float, gnome-calculator"
          ];
          
      };
  };
}
